# Generated by Django 5.2.8 on 2026-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_userhierarchy_all_subs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='requisition_remark_attachments/'),
        ),
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='requisition_remark_attachments/'),
        ),
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='requisition_remark_attachments/'),
        ),
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='attachment_4',
            field=models.FileField(blank=True, null=True, upload_to='requisition_remark_attachments/'),
        ),
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='attachment_5',
            field=models.FileField(blank=True, null=True, upload_to='requisition_remark_attachments/'),
        ),
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='is_fleet_officer_remark',
            field=models.BooleanField(default=False),
        ),
    ]
