# Generated by Django 5.2.8 on 2026-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_attachments_to_vehicle_requisition_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
