# Generated by Django 5.2.8 on 2026-10-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_make_file_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisition',
            name='fleet_officer_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Fleet Officer Remarks'),
        ),
    ]
